### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by hshindo** [hshindo/react-nlp#2]
react-nlpは，以下のような使われ方を想定しています．
あくまでも案なので，改善点・問題点があれば教えてください．
1.  ユーザー（またはjukainlp-webなどの外部Web app）は，アノテーションid, 表示位置，ラベルリスト，をreact-nlpへ事前に与えておく．
2.  ユーザーは，実際のアノテーション情報をreact-nlpへ送る　→　react-nlpがその情報を描画する

使い方の例：
1.

``` javascript
posLabels = {
  "CC": "white",
  "NNP": "#e3e3e3",
  "VBP": "#e3e3e3",
  "JJ": "#fffda8",
}
reactnlp.init("pos", 1, posLabels);

entityLabels = {
 ...
}
reactnlp.init("entity", 2, entityLabels);
```

ここで，アノテーションidが"pos"，表示位置は１，ラベルリストがposLabelsです．
表示位置（整数）は，0を入力テキスト（基準）と考えて，1が入力のすぐ上，2がその上，という絶対位置です．-1は，入力テキストのすぐ下，-2はその下，．．．という具合です．

2.

``` javascript
json = {
    "text": "I have a pen.\nHe is kind",
    "sentence": [
        [1,13], [15,24],
    ],
    "pos": [
        [1,1,"NNP"], [3,6,"VBP"], [8,8,"DT"], [10,13,"NN"],
        [15,16,"NNP"], [18,19,"VBP"], [21,24,"JJ"],
    ],
    "entity": [
        [1,6,"PERSON"], [15,19,"LOCATION"],
    ],
}
reactnlp.show(json);
```

JSONフォーマットは，もう少し修正するかもしれませんが，情報としては上記のようなものをreact-nlpへ送る　→　表示　という具合です．

**Comment by nabeix** [comment]
質問です。

* jsonのsentenceは何を示す情報でしょうか？
* trans_cn等が配列になっていますが、これは行を表すのでしょうか？

**Comment by nabeix** [comment]
ライブラリの使い方についてです。

react-nlpはReactで利用されることを前提としています。
なので、Reactコンポーネントとして機能（テキストにアノテーションを付けて表示）を提供したほうが良いのではないかと思います。
描画に必要な情報はコンポーネントのプロパティとして入力します。

以下のインタフェース（Viewコンポーネント）を提案します。

```
import { Component } from "react";
import { View } from "react-nlp";

class App extends Component {
    render() {
        <div>
            <View data={ data } />
        </div>
    }
}
```

dataの構造についてはjsonの質問と絡むので後ほど提案したいと思います。

**Comment by hshindo** [comment]
sentenceが文の区切りです．例えば，１文字目から13文字目までが１文目です．
trans_cnは，文ごとの翻訳結果なので，文ごとの結果が配列になっています．ひとまずこれは考えなくてよいので一旦削除します．

**Comment by hshindo** [comment]
ライブラリの使い方について，ご提案いただいたもので結構です．
Viewコンポーネントを提供することにします．

**Comment by nabeix** [comment]
> sentenceが文の区切りです．

* 文の区切りと、改行は別のものだと考えてよいでしょうか？
* また、文の区切り情報を使って何かアノテーションを表示することはありますでしょうか？
  * 現状のアノテーションを見ると、全て単語単位で位置指定をしているように見えます。

**Comment by hshindo** [comment]
まず，入力テキストは１つの文字列です．（改行を含む）

改行が文の区切りとは限らないので，文の区切りはサーバー側で決定します．つまり改行とは別物です．

アノテーションは全て文字単位ですが，入力テキストの表示は文単位ですので，文区切り情報が必要です．
結果を表示するときに，文が１行に対応します．（先ほどいただいた画像でも，文を１行として表示していると思います）

**Comment by hshindo** [comment]
文，単語，などの区切りは，英語以外の言語では曖昧な場合があり，各アノテーションの解析プログラム（サーバー側）は，単語ではなく文字を１単位として解析しているので，文字単位の指定範囲を表示できることが望ましいです．

**Comment by nabeix** [comment]
文の区切りはサーバ側で決定し、react-nlpが表示するときは1文1行で表示すると認識しました。

> 文字単位の指定範囲を表示できることが望ましいです．

以前仕様として頂いたサーバからレスポンスされる情報は以下のようになっていました。

```
[
    {
        "text": ["Darth", "Vador", ",", "also", "known", "as", "Anakin", "Skywalker", "is", "a", "fictional", "character", "."],
        "pos": ["1:1:NNP", "2:2:NNP", "3:3:,", "4:4:RB", "5:5:VBN", "6:6:IN"],
        "ne": ["1:2:PERSON", "7:8:PERSON"],
        "wiki": ["1:2:Darth_Vador", "7:8:Darth_Vador"],
        "trans-ja": "ダースベイダー, またはアナキンスカイウォーカーは, 空想のキャラクターだ。"
    },
    {
        "text": ["He", "is", "originally", "a", "good", "person", ",", "but"],
        "pos": ["1:1:PRP", "2:2:VBZ", "3:3:RB", "4:4:DT", "5:5:JJ", "6:6:NN", "7:7:,", "8:8:CC"],
        "trans-ja": "彼はもともと良い人間だった、 しかし"
    }
];
```

ここでは単語単位になっていますが、react-nlpでは文字単位でアノテーションの範囲を指定できることが望ましいという認識でよいでしょうか？

また、react-nlpは改行文字や文の区切りというのを意識せずに、行毎の情報を入力パラメータとし、その通りに表示する方式がシンプルだと思いますが、如何でしょうか？
例えば
```
[
   {  text: "...", annotations: { ... } }, // 1行目の情報
   {  text: "...", annotations: { ... } }  // 2行目の情報
]
```
のような感じです。annotationsには「x文字目（単語目）からy文字目に○○というアノテーションをxx色で表示する」という情報が入ります。

**Comment by hshindo** [comment]
ご提案ありがとうございます。大変助かります。

はい、少々変更があり申し訳ありませんが、少なくとも現状では、範囲指定のアノテーションは文字単位が望ましいです。

ご提案は、
サーバーからのjsonを、jukainlpのほうで文ごとに区切って行単位にするところまでを処理して、それをreactnlpへ入れるということでしょうか？

それならばそれで問題ありません。

ただし、色の設定はreactnlpに処理してもらうほうがうれしいので、あらかじめreactnlpへ、ラベルと色の情報を読み込ませる関数を持たせておきたいと思っています。

**Comment by nabeix** [comment]
> サーバーからのjsonを、jukainlpのほうで文ごとに区切って行単位にするところまでを処理して、それをreactnlpへ入れるということでしょうか？

はい、そのようになります。

> ただし、色の設定はreactnlpに処理してもらうほうがうれしいので、あらかじめreactnlpへ、ラベルと色の情報を読み込ませる関数を持たせておきたいと思っています。

なるほど、一括登録が望ましいということですね。

Viewのプロパティとして指定することもできますが、関数のほうが望ましいでしょうか？

例えばViewにcolorsプロパティを設けて、
```
class App extends Component {
    render() {
        <div>
            <View data={ data } colors={ colors } />
        </div>
    }
}
```
のようにします。

colors変数は、
```
{
  "pos" : {
    "CC": "white",
    "NNP": "#e3e3e3",
    "VBP": "#e3e3e3",
    "JJ": "#fffda8",
  },
  ...
}
```
のような形式になります。

**Comment by nabeix** [comment]
これまでのコメントを踏まえてViewに渡すデータ構造を考えてみました。

```
const data = [
    { // 1行目
        text: "Darth Vador, also known as Anakin Skywalker is a fictional character.", // 文字列
        annotations: [ // アノテーション情報の配列。この順に上から表示される
            {
                type: "wiki", //アノテーション種別
                labels: [
                    { text: "Darth_Vador", from: 0, to: 10 }, // ラベルの文字列と何文字目（from）から何文字目（to）まで範囲指定
                    { text: "Darth_Vador", from: 6, to: 7 }
                ],
            },
            {
                type: "ne",
                labels: [
                    { text: "PERSON", from: 0, to: 1},
                    { text: "PERSION", from: 6, to: 7}
                ],
            },
            {
                type: "pos",
                labels: [
                    { text: "NNP", from: 0, to: 0},
                    { text: "NNP", from: 1, to: 1},
                    { text: ",", from: 2, to: 2}
                ]
            }
        ],
        subText: [
            "ダースベイダー, またはアナキンスカイウォーカーは, 空想のキャラクターだ。" // 一応trans**も考慮してみました。汎用化してsubTextというグルーピングをしています。
        ]
    },
    { // 2行目
        text: "He is originally a good person, but",
        annotations: [
            {
                type: "pos",
                labels: [
                    { label: "PRP", from: 0, to: 0, color: "pink" },
                    { label: "VBZ", from: 1, to: 1, color: "pink" },
                    { label: "RB", from: 2, to: 2, color: "yellow" }
                ]
            }
        ],
        subText: [
            "彼はもともと良い人間だった、しかし"
        ]
    }
];
```

**Comment by hshindo** [comment]
描画速度が遅くならないのであれば、カラープロパティのほうが便利で良いです。
事前に関数で読み込ませるほうが、ずっと描画が速いのであれば関数が好ましいです。

このあたりは、reactの内部処理によるのかもしれないので、私はよくわからないのですが、特に問題が出るまでは、プロパティとして設定することにしたいと思います。
ご提案ありがとうございます。

**Comment by hshindo** [comment]
色やラベルセットの設定をjukainlpではなく、reactnlpで処理したい理由は、
例えば、万が一サーバーからラベルセットに含まれていないラベルが返ってきたとき、対応する色がないので、白色で表示するなどの例外処理が必要になるとおもいます。このような部分は全てのユーザーで共通なので、reactnlpが担当すべき機能だと考えています。

**Comment by nabeix** [comment]
特にパフォーマンス面で影響が出そうにはないので、色指定についてはひとまずViewのプロパティで指定するということにしたいです。

> 対応する色がないので、白色で表示するなどの例外処理が必要になるとおもいます。

はい、こちらは認識していまして、色指定がない場合は白色ということにしておきます。

**Comment by hshindo** [comment]
はい，ではそれでお願いします．

jsonは，以下のように配列を使って，

```javascript
{
  [
    // 1文目
    text: "Darth Vador, also known as Anakin Skywalker is a fictional character.",
    anno: [
      ["wiki", 0, 10, "Darth Vador"],
      ["ne", 0, 1, "PERSON"],
      ["pos", 0, 0, "NNP"].
    ]
  ],
  [
    // 2文目
    text: "He is originally a good person, but",
    anno: [
      ["pos", 0, 0, "PRP"],
    ]
  ],
}
```
というようにしたいと思います．
我々の分野ではこのような書き方が一般的なので，辞書のキー・バリューよりもこのほうが良いです．

**Comment by nabeix** [comment]
了解しました。そのようなインタフェースで問題ありません 👍

**Comment by hshindo** [comment]
サーバー側の出力を，上記のフォーマットと整合性が高いように変更しますので，完成次第ご連絡します．

**Comment by nabeix** [comment]
お願いします。

**Comment by nabeix** [comment]
```
 anno: [
      ["wiki", 0, 10, "Darth Vador"],
      ["ne", 0, 1, "PERSON"],
      ["pos", 0, 0, "NNP"].
    ]
```

この部分ですが、アノテーションを増やすと、

```
 anno: [
      ["wiki", 0, 10, "Darth Vador"],
      ["ne", 0, 1, "PERSON"],
      ["pos", 0, 0, "NNP"],
      ["pos", 2, 3, "NNP"],
      ["wiki", 4, 12, "Darth Vador"]
    ]
```

となっていくかと思います。

アノテーション種別（wiki, ne, pos）をそれぞれ別の行で表示しますが、
この構造だとwikiとneとposをどの順番で表示するか決められないと思うのですが如何でしょうか？
アノテーション種別の出現順にするというのもひとつの手（この場合だとwiki -> ne -> posの順になる）ですが、インタフェース的には分かりにくいと思います。

**Comment by hshindo** [comment]
そういった部分は，アノテーションの問題ではなくて表示の問題なので，ラベル・色設定と一緒に情報を渡したいと思っています．
colorsという引数を，configに変えて，ラベル・色・位置をまとめてjsonで指定したいと思います．

**Comment by nabeix** [comment]
> colorsという引数を，configに変えて，ラベル・色・位置をまとめてjsonで指定したいと思います．

```
{
  order: ["pos", "wiki", "ne"],
  colors: {
    pos : {
    CC: "white",
    NNP: "#e3e3e3",
    VBP: "#e3e3e3",
    JJ: "#fffda8"
  },
  ...
}
```
みたいな感じでしょうか。
この程度であればconfigにまとめずに、orderとcolors別々に指定させても良いような気がします。

並び順が未指定の場合の挙動はどうしましょうか？

**Comment by nabeix** [comment]
orderというとただの並び順になってしまうので、この Viewで使うアノテーション種別（？）はこれだ、と指定させるほうが良いと思いました。
であれば、指定されてないものは表示されてないという仕様にできそうです。
```
<View types={["wiki", "ne", "pos"}} colors={colors} data={data} />
```

如何でしょうか？

**Comment by hshindo** [comment]
有難うございます．
概ねそのような感じなのですが，詳細は少し考えさせてください．

**Comment by hshindo** [comment]
色指定は，ひとまず上記の
```javascript
<View types={["wiki", "ne", "pos"}} colors={colors} data={data} />
```
でお願いします．
変更がありましたらご連絡します．

**Comment by nabeix** [comment]
了解しました
